
/*This file is generated by code generator*/

#include "screensaver.h"
#include "mvvm/base/view_model.h"

#ifndef TK_SCREENSAVER_VIEW_MODEL_H
#define TK_SCREENSAVER_VIEW_MODEL_H

BEGIN_C_DECLS
/**
 * @class screensaver_view_model_t
 *
 * view model of screensaver
 *
 */
typedef struct _screensaver_view_model_t {
  view_model_t view_model;

  /*model object*/
  screensaver_t* ascreensaver;
} screensaver_view_model_t;

/**
 * @method screensaver_view_model_create
 * 创建screensaver view model对象。
 *
 * @annotation ["constructor"]
 * @param {navigator_request_t*} req 请求参数。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* screensaver_view_model_create(navigator_request_t* req);

/**
 * @method screensaver_view_model_create_with
 * 创建screensaver view model对象。
 *
 * @annotation ["constructor"]
 * @param {screensaver_t*}  ascreensaver screensaver对象。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* screensaver_view_model_create_with(screensaver_t* ascreensaver);

/**
 * @method screensaver_view_model_attach
 * 关联到screensaver对象。
 *
 * @param {view_model_t*} view_model view_model对象。
 * @param {screensaver_t*} screensaver screensaver对象。
 *
 * @return {ret_t} 返回RET_OK表示成功，否则表示失败。
 */
ret_t screensaver_view_model_attach(view_model_t* vm, screensaver_t* ascreensaver);

END_C_DECLS

#endif /*TK_SCREENSAVER_VIEW_MODEL_H*/
