
/*This file is generated by code generator*/

#include "home.h"
#include "mvvm/base/view_model.h"

#ifndef TK_HOME_VIEW_MODEL_H
#define TK_HOME_VIEW_MODEL_H

BEGIN_C_DECLS
/**
 * @class home_view_model_t
 *
 * view model of home
 *
 */
typedef struct _home_view_model_t {
  view_model_t view_model;

  /*model object*/
  home_t* ahome;
} home_view_model_t;

/**
 * @method home_view_model_create
 * 创建home view model对象。
 *
 * @annotation ["constructor"]
 * @param {navigator_request_t*} req 请求参数。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* home_view_model_create(navigator_request_t* req);

/**
 * @method home_view_model_create_with
 * 创建home view model对象。
 *
 * @annotation ["constructor"]
 * @param {home_t*}  ahome home对象。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* home_view_model_create_with(home_t* ahome);

/**
 * @method home_view_model_attach
 * 关联到home对象。
 *
 * @param {view_model_t*} view_model view_model对象。
 * @param {home_t*} home home对象。
 *
 * @return {ret_t} 返回RET_OK表示成功，否则表示失败。
 */
ret_t home_view_model_attach(view_model_t* vm, home_t* ahome);

END_C_DECLS

#endif /*TK_HOME_VIEW_MODEL_H*/
