
/*This file is generated by code generator*/

#include "tkc/mem.h"
#include "tkc/utils.h"
#include "mvvm/base/utils.h"
#include "room_settings_view_model.h"

static ret_t room_settings_view_model_set_prop(tk_object_t* obj, const char* name,
                                               const value_t* v) {
  room_settings_t* aroom_settings = ((room_settings_view_model_t*)(obj))->aroom_settings;

  if (tk_str_ieq("temp", name)) {
    aroom_settings->temp = value_double(v);

    return RET_OK;
  } else if (tk_str_ieq("humidity", name)) {
    aroom_settings->humidity = value_double(v);

    return RET_OK;
  } else if (tk_str_ieq("room", name)) {
    aroom_settings->room = tk_str_copy(aroom_settings->room, value_str(v));

    return RET_OK;
  }

  return RET_NOT_FOUND;
}

static ret_t room_settings_view_model_get_prop(tk_object_t* obj, const char* name, value_t* v) {
  room_settings_t* aroom_settings = ((room_settings_view_model_t*)(obj))->aroom_settings;

  if (tk_str_ieq("temp", name)) {
    value_set_double(v, aroom_settings->temp);
    return RET_OK;
  } else if (tk_str_ieq("humidity", name)) {
    value_set_double(v, aroom_settings->humidity);
    return RET_OK;
  } else if (tk_str_ieq("room", name)) {
    value_set_str(v, aroom_settings->room);
    return RET_OK;
  }

  return RET_NOT_FOUND;
}

static bool_t room_settings_view_model_can_exec(tk_object_t* obj, const char* name,
                                                const char* args) {
  room_settings_view_model_t* vm = (room_settings_view_model_t*)(obj);
  room_settings_t* aroom_settings = vm->aroom_settings;
  if (tk_str_ieq("return", name)) {
    return TRUE;
  }
  return FALSE;
}

static ret_t room_settings_view_model_exec(tk_object_t* obj, const char* name, const char* args) {
  room_settings_view_model_t* vm = (room_settings_view_model_t*)(obj);
  room_settings_t* aroom_settings = vm->aroom_settings;
  if (tk_str_ieq("return", name)) {
    return room_settings_return(aroom_settings);
  }
  return RET_NOT_FOUND;
}

static ret_t room_settings_view_model_on_destroy(tk_object_t* obj) {
  room_settings_view_model_t* vm = (room_settings_view_model_t*)(obj);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  room_settings_destroy(vm->aroom_settings);

  return view_model_deinit(VIEW_MODEL(obj));
}

static const object_vtable_t s_room_settings_view_model_vtable = {
    "room_settings_view_model_t",
    "room_settings_view_model_t",
    sizeof(room_settings_view_model_t),
    FALSE,
    room_settings_view_model_on_destroy,
    NULL,
    room_settings_view_model_get_prop,
    room_settings_view_model_set_prop,
    NULL,
    NULL,
    room_settings_view_model_can_exec,
    room_settings_view_model_exec};

view_model_t* room_settings_view_model_create_with(room_settings_t* aroom_settings) {
  tk_object_t* obj = tk_object_create(&s_room_settings_view_model_vtable);
  view_model_t* vm = view_model_init(VIEW_MODEL(obj));
  room_settings_view_model_t* room_settings_view_model = (room_settings_view_model_t*)(vm);

  return_value_if_fail(vm != NULL, NULL);

  room_settings_view_model->aroom_settings = aroom_settings;

  return vm;
}

ret_t room_settings_view_model_attach(view_model_t* vm, room_settings_t* aroom_settings) {
  room_settings_view_model_t* room_settings_view_model = (room_settings_view_model_t*)(vm);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  room_settings_view_model->aroom_settings = aroom_settings;

  return RET_OK;
}

view_model_t* room_settings_view_model_create(navigator_request_t* req) {
  room_settings_t* aroom_settings = room_settings_create(req);
  return_value_if_fail(aroom_settings != NULL, NULL);

  return room_settings_view_model_create_with(aroom_settings);
}
