
/*This file is generated by code generator*/

#include "tkc/mem.h"
#include "tkc/utils.h"
#include "mvvm/base/utils.h"
#include "book_view_model.h"

static ret_t book_view_model_set_prop(tk_object_t* obj, const char* name, const value_t* v) {
  Book* aBook = ((book_view_model_t*)(obj))->aBook;

  if (tk_str_ieq("name", name)) {
    aBook->name = value_str(v);

    return RET_OK;
  } else if (tk_str_ieq("stock", name)) {
    aBook->stock = value_uint32(v);

    return RET_OK;
  }

  return RET_NOT_FOUND;
}

static ret_t book_view_model_get_prop(tk_object_t* obj, const char* name, value_t* v) {
  Book* aBook = ((book_view_model_t*)(obj))->aBook;

  if (tk_str_ieq("name", name)) {
    value_set_str(v, aBook->name.c_str());
    return RET_OK;
  } else if (tk_str_ieq("stock", name)) {
    value_set_uint32(v, aBook->stock);
    return RET_OK;
  }

  return RET_NOT_FOUND;
}

static bool_t book_view_model_can_exec(tk_object_t* obj, const char* name, const char* args) {
  book_view_model_t* vm = (book_view_model_t*)(obj);
  Book* aBook = vm->aBook;
  if (tk_str_ieq("Sale", name)) {
    return aBook->CanSale();
  }
  return FALSE;
}

static ret_t book_view_model_exec(tk_object_t* obj, const char* name, const char* args) {
  book_view_model_t* vm = (book_view_model_t*)(obj);
  Book* aBook = vm->aBook;
  if (tk_str_ieq("Sale", name)) {
    return aBook->Sale();
  }
  return RET_NOT_FOUND;
}

static ret_t book_view_model_on_destroy(tk_object_t* obj) {
  book_view_model_t* vm = (book_view_model_t*)(obj);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  delete (vm->aBook);

  return view_model_deinit(VIEW_MODEL(obj));
}

static const struct book_view_model_vtable_t {
  object_vtable_t base;
  book_view_model_vtable_t() {
    base.type = "book_view_model_t";
    base.desc = "book_view_model_t";
    base.size = sizeof(book_view_model_t);
    base.is_collection = FALSE;
    base.on_destroy = book_view_model_on_destroy;
    base.get_prop = book_view_model_get_prop;
    base.set_prop = book_view_model_set_prop;
    base.can_exec = book_view_model_can_exec;
    base.exec = book_view_model_exec;
  }
} s_book_view_model_vtable;

view_model_t* book_view_model_create_with(Book* aBook) {
  tk_object_t* obj = tk_object_create(&s_book_view_model_vtable.base);
  view_model_t* vm = view_model_init(VIEW_MODEL(obj));
  book_view_model_t* book_view_model = (book_view_model_t*)(vm);

  return_value_if_fail(vm != NULL, NULL);

  book_view_model->aBook = aBook;

  return vm;
}

ret_t book_view_model_attach(view_model_t* vm, Book* aBook) {
  book_view_model_t* book_view_model = (book_view_model_t*)(vm);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  book_view_model->aBook = aBook;

  return RET_OK;
}

view_model_t* book_view_model_create(navigator_request_t* req) {
  Book* aBook = new Book();
  return_value_if_fail(aBook != NULL, NULL);

  return book_view_model_create_with(aBook);
}
