
/*This file is generated by code generator*/

#include "book_store.h"
#include "book_view_model.h"
#include "mvvm/base/view_model_array.h"

#ifndef TK_BOOKSTORE_VIEW_MODEL_H
#define TK_BOOKSTORE_VIEW_MODEL_H

BEGIN_C_DECLS
/**
 * @class book_store_view_model_t
 *
 * view model of BookStore
 *
 */
typedef struct _book_store_view_model_t {
  view_model_array_t view_model_array;

  /*model object*/
  BookStore* aBookStore;
  view_model_t* book_view_model;
} book_store_view_model_t;

/**
 * @method book_store_view_model_create
 * 创建BookStore view model对象。
 *
 * @annotation ["constructor"]
 * @param {navigator_request_t*} req 请求参数。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* book_store_view_model_create(navigator_request_t* req);

/**
 * @method book_store_view_model_create_with
 * 创建BookStore view model对象。
 *
 * @annotation ["constructor"]
 * @param {BookStore*}  aBookStore BookStore对象。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* book_store_view_model_create_with(BookStore* aBookStore);

END_C_DECLS

#endif /*TK_BOOKSTORE_VIEW_MODEL_H*/
