
/*This file is generated by code generator*/

#include "tkc/mem.h"
#include "tkc/utils.h"
#include "mvvm/base/utils.h"
#include "humidity_view_model.h"

static ret_t humidity_view_model_set_prop(tk_object_t* obj, const char* name, const value_t* v) {
  if (tk_str_ieq("humi", name)) {
    return RET_OK;
  }

  return RET_NOT_FOUND;
}

static ret_t humidity_view_model_get_prop(tk_object_t* obj, const char* name, value_t* v) {
  if (tk_str_ieq("humi", name)) {
    value_set_double(v, 321);
    return RET_OK;
  }

  return RET_NOT_FOUND;
}

static bool_t humidity_view_model_can_exec(tk_object_t* obj, const char* name, const char* args) {
  if (tk_str_ieq("apply_humi", name)) {
    return TRUE;
  }
  return FALSE;
}

static ret_t humidity_view_model_exec(tk_object_t* obj, const char* name, const char* args) {
  if (tk_str_ieq("apply_humi", name)) {
    return RET_OK;
  }
  return RET_NOT_FOUND;
}

static ret_t humidity_view_model_on_destroy(tk_object_t* obj) {
  humidity_view_model_t* vm = (humidity_view_model_t*)(obj);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  return view_model_deinit(VIEW_MODEL(obj));
}

static const object_vtable_t s_humidity_view_model_vtable = {.type = "humidity_view_model_t",
                                                             .desc = "humidity_view_model_t",
                                                             .size = sizeof(humidity_view_model_t),
                                                             .on_destroy = humidity_view_model_on_destroy,
                                                             .get_prop = humidity_view_model_get_prop,
                                                             .set_prop = humidity_view_model_set_prop,
                                                             .can_exec = humidity_view_model_can_exec,
                                                             .exec = humidity_view_model_exec};

view_model_t* humidity_view_model_create(navigator_request_t* req) {
  tk_object_t* obj = tk_object_create(&s_humidity_view_model_vtable);
  view_model_t* vm = view_model_init(VIEW_MODEL(obj));

  return vm;
}
