import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

env['LIBS'] = ['jerryscript'] + ['common'] + env['LIBS']

env.Program(os.path.join(BIN_DIR, 'mvvm_factory_gen'), ["mvvm_factory_gen.c"])