
/*This file is generated by code generator*/

#include "tkc/mem.h"
#include "tkc/utils.h"
#include "mvvm/base/utils.h"
#include "humidity_view_model.h"

static ret_t humidity_view_model_set_prop(object_t* obj, const char* name, const value_t* v) {
  humidity_t* humidity = ((humidity_view_model_t*)(obj))->humidity;

  if (tk_str_eq("value", name)) {
     humidity->value = value_double(v);

     return RET_OK;
  }
  
  return RET_NOT_FOUND;
}


static ret_t humidity_view_model_get_prop(object_t* obj, const char* name, value_t* v) {
  humidity_t* humidity = ((humidity_view_model_t*)(obj))->humidity;

  if (tk_str_eq("value", name)) {
     value_set_double(v, humidity->value);
     return RET_OK;
  }

  return RET_NOT_FOUND;
}


static bool_t humidity_view_model_can_exec(object_t* obj, const char* name, const char* args) {
 
  humidity_view_model_t* vm = (humidity_view_model_t*)(obj);
  humidity_t* humidity = vm->humidity;
  if (tk_str_eq("apply", name)) {
    return humidity_can_apply(humidity);
  }
  return FALSE;
}

static ret_t humidity_view_model_exec(object_t* obj, const char* name, const char* args) {
 
  humidity_view_model_t* vm = (humidity_view_model_t*)(obj);
  humidity_t* humidity = vm->humidity;
  if (tk_str_eq("apply", name)) {
    humidity_apply(humidity);
    return RET_OBJECT_CHANGED;
  }
  return RET_NOT_FOUND;
}

static ret_t humidity_view_model_on_destroy(object_t* obj) {
  humidity_view_model_t* vm = (humidity_view_model_t*)(obj);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  humidity_destroy(vm->humidity);

  return view_model_deinit(VIEW_MODEL(obj));
}

static const object_vtable_t s_humidity_view_model_vtable = {
  .type = "humidity_view_model_t",
  .desc = "humidity_view_model_t",
  .size = sizeof(humidity_view_model_t),
  .exec = humidity_view_model_exec,
  .can_exec = humidity_view_model_can_exec,
  .get_prop = humidity_view_model_get_prop,
  .set_prop = humidity_view_model_set_prop,
  .on_destroy = humidity_view_model_on_destroy
};

view_model_t* humidity_view_model_create_with(humidity_t* humidity) {
  object_t* obj = object_create(&s_humidity_view_model_vtable);
  view_model_t* vm = view_model_init(VIEW_MODEL(obj));
  humidity_view_model_t* humidity_view_model = (humidity_view_model_t*)(vm);

  return_value_if_fail(vm != NULL, NULL);

  humidity_view_model->humidity = humidity;
  ENSURE(humidity_view_model->humidity != NULL);

  return vm;
}

ret_t humidity_view_model_attach(view_model_t* vm, humidity_t* humidity) {
  humidity_view_model_t* humidity_view_model = (humidity_view_model_t*)(vm);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  humidity_view_model->humidity = humidity;

  return RET_OK;
}

view_model_t* humidity_view_model_create(navigator_request_t* req) {
  return humidity_view_model_create_with(humidity_create());
}
