import os   
import platform
CPPPATH=[]
sources=[]
env=DefaultEnvironment().Clone()
OS_NAME=platform.system()
LIB_DIR=os.environ['LIB_DIR'];

CPPPATH=['nativefiledialog/src', 'nativefiledialog/src/include']

sources=['nativefiledialog/src/nfd_common.c']
if OS_NAME == 'Windows':
  sources+=['nativefiledialog/src/nfd_win.cpp']
elif OS_NAME == 'Linux':
  sources+=['nativefiledialog/src/nfd_zenity.c', 'nativefiledialog/src/nfd_gtk.c']
elif OS_NAME == 'Darwin':
  sources+=['nativefiledialog/src/nfd_cocoa.m']

CCFLAGS=os.environ['CCFLAGS'];
env.Library(os.path.join(LIB_DIR, 'nfd'), sources, CPPPATH = CPPPATH, CCFLAGS = CCFLAGS)

