
/*This file is generated by code generator*/

#include "tkc/mem.h"
#include "tkc/utils.h"
#include "tkc/object_array.h"
#include "mvvm/base/utils.h"
#include "humidity.h"
#include "temperature.h"
#include "temperature_humidity_view_model.h"

static ret_t temperature_humidity_view_model_on_create(view_model_t* view_model,
                                                       navigator_request_t* req) {
  value_t v;
  tk_object_t* obj;
  temperature_humidity_view_model_t* vm = (temperature_humidity_view_model_t*)(view_model);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  obj = temperature_create();
  vm->outside_temperature = obj;
  emitter_on(EMITTER(obj), EVT_PROP_CHANGED, emitter_forward, vm);

  obj = humidity_create();
  vm->outside_humidity = obj;
  emitter_on(EMITTER(obj), EVT_PROP_CHANGED, emitter_forward, vm);

  vm->inside_temperatures = object_array_create();

  obj = temperature_create();
  value_set_object(&v, obj);
  object_array_push(vm->inside_temperatures, &v);
  emitter_on(EMITTER(obj), EVT_PROP_CHANGED, emitter_forward, vm);
  TK_OBJECT_UNREF(obj);

  obj = temperature_create();
  value_set_object(&v, obj);
  object_array_push(vm->inside_temperatures, &v);
  emitter_on(EMITTER(obj), EVT_PROP_CHANGED, emitter_forward, vm);
  TK_OBJECT_UNREF(obj);

  vm->inside_humidities = object_array_create();

  obj = humidity_create();
  value_set_object(&v, obj);
  object_array_push(vm->inside_humidities, &v);
  emitter_on(EMITTER(obj), EVT_PROP_CHANGED, emitter_forward, vm);
  TK_OBJECT_UNREF(obj);

  obj = humidity_create();
  value_set_object(&v, obj);
  object_array_push(vm->inside_humidities, &v);
  emitter_on(EMITTER(obj), EVT_PROP_CHANGED, emitter_forward, vm);
  TK_OBJECT_UNREF(obj);

  return RET_OK;
}

static ret_t temperature_humidity_view_model_on_destroy(tk_object_t* obj) {
  temperature_humidity_view_model_t* vm = (temperature_humidity_view_model_t*)(obj);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  TK_OBJECT_UNREF(vm->outside_humidity);
  TK_OBJECT_UNREF(vm->outside_temperature);
  TK_OBJECT_UNREF(vm->inside_humidities);
  TK_OBJECT_UNREF(vm->inside_temperatures);

  return view_model_deinit(VIEW_MODEL(obj));
}

static ret_t temperature_humidity_view_model_set_prop(tk_object_t* obj, const char* name,
                                                      const value_t* v) {
  temperature_humidity_view_model_t* vm = ((temperature_humidity_view_model_t*)(obj));

  tk_object_t* sub = tk_object_get_child_object(obj, name, &name);
  if (sub != NULL) {
    return tk_object_set_prop(sub, name, v);
  }

  if (tk_str_ieq("outside_temp", name)) {
    return tk_object_set_prop(vm->outside_temperature, "temp", v);
  } else if (tk_str_ieq("outside_humi", name)) {
    return tk_object_set_prop(vm->outside_humidity, "humi", v);
  }

  return RET_NOT_FOUND;
}

static ret_t temperature_humidity_view_model_get_prop(tk_object_t* obj, const char* name,
                                                      value_t* v) {
  temperature_humidity_view_model_t* vm = ((temperature_humidity_view_model_t*)(obj));

  tk_object_t* sub = tk_object_get_child_object(obj, name, &name);
  if (sub != NULL) {
    return tk_object_get_prop(sub, name, v);
  }

  if (tk_str_ieq("outside_temperature", name)) {
    value_set_object(v, vm->outside_temperature);
    return RET_OK;
  } else if (tk_str_ieq("outside_humidity", name)) {
    value_set_object(v, vm->outside_humidity);
    return RET_OK;
  } else if (tk_str_ieq("inside_temperatures", name)) {
    value_set_object(v, vm->inside_temperatures);
    return RET_OK;
  } else if (tk_str_ieq("inside_humidities", name)) {
    value_set_object(v, vm->inside_humidities);
    return RET_OK;
  } else if (tk_str_ieq("outside_temp", name)) {
    return tk_object_get_prop(vm->outside_temperature, "temp", v);
  } else if (tk_str_ieq("outside_humi", name)) {
    return tk_object_get_prop(vm->outside_humidity, "humi", v);
  }

  return RET_NOT_FOUND;
}

static bool_t temperature_humidity_view_model_can_exec(tk_object_t* obj, const char* name,
                                                       const char* args) {
  temperature_humidity_view_model_t* vm = (temperature_humidity_view_model_t*)(obj);
  return_value_if_fail(vm != NULL, FALSE);

  tk_object_t* sub = tk_object_get_child_object(obj, name, &name);
  if (sub != NULL) {
    return tk_object_can_exec(sub, name, args);
  }

  if (tk_str_ieq("outside_temp_reset", name)) {
    return tk_object_can_exec(vm->outside_temperature, "reset", args);
  } else if (tk_str_ieq("outside_humi_apply", name)) {
    return tk_object_can_exec(vm->outside_humidity, "apply", args);
  }
  return FALSE;
}

static ret_t temperature_humidity_view_model_exec(tk_object_t* obj, const char* name,
                                                  const char* args) {
  temperature_humidity_view_model_t* vm = (temperature_humidity_view_model_t*)(obj);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  tk_object_t* sub = tk_object_get_child_object(obj, name, &name);
  if (sub != NULL) {
    return tk_object_exec(sub, name, args);
  }

  if (tk_str_ieq("outside_temp_reset", name)) {
    return tk_object_exec(vm->outside_temperature, "reset", args);
  } else if (tk_str_ieq("outside_humi_apply", name)) {
    return tk_object_exec(vm->outside_humidity, "apply", args);
  }
  return RET_NOT_FOUND;
}

static const object_vtable_t s_humidity_view_model_vtable = {
    .type = "temperature_humidity_view_model_t",
    .desc = "temperature_humidity_view_model_t",
    .size = sizeof(temperature_humidity_view_model_t),
    .on_destroy = temperature_humidity_view_model_on_destroy,
    .get_prop = temperature_humidity_view_model_get_prop,
    .set_prop = temperature_humidity_view_model_set_prop,
    .can_exec = temperature_humidity_view_model_can_exec,
    .exec = temperature_humidity_view_model_exec};

view_model_t* temperature_humidity_view_model_create(navigator_request_t* req) {
  tk_object_t* obj = tk_object_create(&s_humidity_view_model_vtable);
  view_model_t* view_model = view_model_init(VIEW_MODEL(obj));
  return_value_if_fail(view_model != NULL, NULL);

  temperature_humidity_view_model_on_create(view_model, req);

  return view_model;
}
