
/*This file is generated by code generator*/

#include "mvvm/base/view_model.h"

#ifndef TK_TEMPERATURE_HUMIDITY_VIEW_MODEL_H
#define TK_TEMPERATURE_HUMIDITY_VIEW_MODEL_H

BEGIN_C_DECLS
/**
 * @class temperature_humidity_view_model_t
 *
 * view model of temperature-humidity
 *
 */
typedef struct _temperature_humidity_view_model_t {
  view_model_t view_model;

  /*model object*/
  tk_object_t* outside_humidity;
  tk_object_t* outside_temperature;
  tk_object_t* inside_humidities;
  tk_object_t* inside_temperatures;
} temperature_humidity_view_model_t;

/**
 * @method temperature_humidity_view_model
 * 创建temperature-humidity view model对象。
 *
 * @annotation ["constructor"]
 * @param {navigator_request_t*} req 请求参数。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* temperature_humidity_view_model_create(navigator_request_t* req);

END_C_DECLS

#endif /*TK_TEMPERATURE_HUMIDITY_VIEW_MODEL_H*/
