
/*This file is generated by code generator*/

#include "tkc/mem.h"
#include "tkc/utils.h"
#include "tkc/object_array.h"
#include "mvvm/base/utils.h"
#include "humidity.h"
#include "temperature.h"
#include "temperature_humidity_view_model.h"

static ret_t temperature_humidity_view_model_on_create(view_model_t* view_model,
                                                       navigator_request_t* req) {
  object_t* obj;
  temperature_humidity_view_model_t* vm = (temperature_humidity_view_model_t*)(view_model);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  obj = temperature_create();
  vm->outside_temperature = obj;
  emitter_on(EMITTER(obj), EVT_PROP_CHANGED, (event_func_t)emitter_dispatch, vm);

  obj = humidity_create();
  vm->outside_humidity = obj;
  emitter_on(EMITTER(obj), EVT_PROP_CHANGED, (event_func_t)emitter_dispatch, vm);

  vm->inside_temperatures = object_array_create();

  obj = temperature_create();
  object_set_prop_object(vm->inside_temperatures, "-1", obj);
  emitter_on(EMITTER(obj), EVT_PROP_CHANGED, (event_func_t)emitter_dispatch, vm);
  OBJECT_UNREF(obj);

  obj = temperature_create();
  object_set_prop_object(vm->inside_temperatures, "-1", obj);
  emitter_on(EMITTER(obj), EVT_PROP_CHANGED, (event_func_t)emitter_dispatch, vm);
  OBJECT_UNREF(obj);

  vm->inside_humidities = object_array_create();

  obj = humidity_create();
  object_set_prop_object(vm->inside_humidities, "-1", obj);
  emitter_on(EMITTER(obj), EVT_PROP_CHANGED, (event_func_t)emitter_dispatch, vm);
  OBJECT_UNREF(obj);

  obj = humidity_create();
  object_set_prop_object(vm->inside_humidities, "-1", obj);
  emitter_on(EMITTER(obj), EVT_PROP_CHANGED, (event_func_t)emitter_dispatch, vm);
  OBJECT_UNREF(obj);

  return RET_OK;
}

static ret_t temperature_humidity_view_model_on_destroy(object_t* obj) {
  temperature_humidity_view_model_t* vm = (temperature_humidity_view_model_t*)(obj);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  OBJECT_UNREF(vm->outside_humidity);
  OBJECT_UNREF(vm->outside_temperature);
  OBJECT_UNREF(vm->inside_humidities);
  OBJECT_UNREF(vm->inside_temperatures);

  return view_model_deinit(VIEW_MODEL(obj));
}

static ret_t temperature_humidity_view_model_set_prop(object_t* obj, const char* name,
                                                      const value_t* v) {
  temperature_humidity_view_model_t* vm = ((temperature_humidity_view_model_t*)(obj));

  if (tk_str_ieq("outside_temp", name)) {
    return object_set_prop(vm->outside_temperature, "temp", v);
  } else if (tk_str_ieq("outside_humi", name)) {
    return object_set_prop(vm->outside_humidity, "humi", v);
  }

  return RET_NOT_FOUND;
}

static ret_t temperature_humidity_view_model_get_prop(object_t* obj, const char* name, value_t* v) {
  temperature_humidity_view_model_t* vm = ((temperature_humidity_view_model_t*)(obj));

  if (tk_str_ieq("outside_temperature", name)) {
    value_set_object(v, vm->outside_temperature);
    return RET_OK;
  } else if (tk_str_ieq("outside_humidity", name)) {
    value_set_object(v, vm->outside_humidity);
    return RET_OK;
  } else if (tk_str_ieq("inside_temperatures", name)) {
    value_set_object(v, vm->inside_temperatures);
    return RET_OK;
  } else if (tk_str_ieq("inside_humidities", name)) {
    value_set_object(v, vm->inside_humidities);
    return RET_OK;
  } else if (tk_str_ieq("outside_temp", name)) {
    return object_get_prop(vm->outside_temperature, "temp", v);
  } else if (tk_str_ieq("outside_humi", name)) {
    return object_get_prop(vm->outside_humidity, "humi", v);
  }

  return RET_NOT_FOUND;
}

static bool_t temperature_humidity_view_model_can_exec(object_t* obj, const char* name,
                                                       const char* args) {
  temperature_humidity_view_model_t* vm = (temperature_humidity_view_model_t*)(obj);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  if (tk_str_ieq("outside_temp_reset", name)) {
    return object_can_exec(vm->outside_temperature, "reset", args);
  } else if (tk_str_ieq("outside_humi_apply", name)) {
    return object_can_exec(vm->outside_humidity, "apply", args);
  }
  return FALSE;
}

static ret_t temperature_humidity_view_model_exec(object_t* obj, const char* name,
                                                  const char* args) {
  temperature_humidity_view_model_t* vm = (temperature_humidity_view_model_t*)(obj);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  if (tk_str_ieq("outside_temp_reset", name)) {
    return object_exec(vm->outside_temperature, "reset", args);
  } else if (tk_str_ieq("outside_humi_apply", name)) {
    return object_exec(vm->outside_humidity, "apply", args);
  }
  return RET_NOT_FOUND;
}

static const object_vtable_t s_humidity_view_model_vtable = {
    "temperature_humidity_view_model_t",
    "temperature_humidity_view_model_t",
    sizeof(temperature_humidity_view_model_t),
    FALSE,
    temperature_humidity_view_model_on_destroy,
    NULL,
    temperature_humidity_view_model_get_prop,
    temperature_humidity_view_model_set_prop,
    NULL,
    NULL,
    temperature_humidity_view_model_can_exec,
    temperature_humidity_view_model_exec};

view_model_t* temperature_humidity_view_model_create(navigator_request_t* req) {
  object_t* obj = object_create(&s_humidity_view_model_vtable);
  view_model_t* view_model = view_model_init(VIEW_MODEL(obj));
  return_value_if_fail(view_model != NULL, NULL);

  temperature_humidity_view_model_on_create(view_model, req);

  return view_model;
}
