
/*This file is generated by code generator*/

#include "tkc/mem.h"
#include "tkc/utils.h"
#include "mvvm/base/utils.h"
#include "humidity_view_model.h"

static ret_t humidity_view_model_set_prop(object_t* obj, const char* name, const value_t* v) {
  humidity_t* ahumidity = ((humidity_view_model_t*)(obj))->ahumidity;

  if (tk_str_ieq("humi", name)) {
    ahumidity->humi = value_double(v);

    return RET_OK;
  }

  return RET_NOT_FOUND;
}

static ret_t humidity_view_model_get_prop(object_t* obj, const char* name, value_t* v) {
  humidity_t* ahumidity = ((humidity_view_model_t*)(obj))->ahumidity;

  if (tk_str_ieq("humi", name)) {
    value_set_double(v, ahumidity->humi);
    return RET_OK;
  }

  return RET_NOT_FOUND;
}

static bool_t humidity_view_model_can_exec(object_t* obj, const char* name, const char* args) {
  return FALSE;
}

static ret_t humidity_view_model_exec(object_t* obj, const char* name, const char* args) {
  return RET_NOT_FOUND;
}

static ret_t humidity_view_model_on_destroy(object_t* obj) {
  humidity_view_model_t* vm = (humidity_view_model_t*)(obj);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  TKMEM_FREE(vm->ahumidity);

  return view_model_deinit(VIEW_MODEL(obj));
}

static const object_vtable_t s_humidity_view_model_vtable = {"humidity_view_model_t",
                                                             "humidity_view_model_t",
                                                             sizeof(humidity_view_model_t),
                                                             FALSE,
                                                             humidity_view_model_on_destroy,
                                                             NULL,
                                                             humidity_view_model_get_prop,
                                                             humidity_view_model_set_prop,
                                                             NULL,
                                                             NULL,
                                                             humidity_view_model_can_exec,
                                                             humidity_view_model_exec};

view_model_t* humidity_view_model_create_with(humidity_t* ahumidity) {
  object_t* obj = object_create(&s_humidity_view_model_vtable);
  view_model_t* vm = view_model_init(VIEW_MODEL(obj));
  humidity_view_model_t* humidity_view_model = (humidity_view_model_t*)(vm);

  return_value_if_fail(vm != NULL, NULL);

  humidity_view_model->ahumidity = ahumidity;

  return vm;
}

ret_t humidity_view_model_attach(view_model_t* vm, humidity_t* ahumidity) {
  humidity_view_model_t* humidity_view_model = (humidity_view_model_t*)(vm);
  return_value_if_fail(vm != NULL, RET_BAD_PARAMS);

  humidity_view_model->ahumidity = ahumidity;

  return RET_OK;
}

view_model_t* humidity_view_model_create(navigator_request_t* req) {
  humidity_t* ahumidity = TKMEM_ZALLOC(humidity_t);
  return_value_if_fail(ahumidity != NULL, NULL);

  return humidity_view_model_create_with(ahumidity);
}
