
/*This file is generated by code generator*/

#include "tkc/str.h"
#include "mvvm/base/view_model.h"

#ifndef TK_ADDRESS_VIEW_MODEL_H
#define TK_ADDRESS_VIEW_MODEL_H

BEGIN_C_DECLS
/**
 * @class address_view_model_t
 *
 * view model of address
 *
 */
typedef struct _address_view_model_t {
  view_model_t view_model;

  /*model object*/
  char* province_list;
  char* city_list;
  char* country_list;
  char* province;
  char* city;
  char* country;
  char* detail;
  str_t temp;
} address_view_model_t;

/**
 * @method address_view_model_create
 * 创建address view model对象。
 *
 * @annotation ["constructor"]
 * @param {navigator_request_t*} req 请求参数。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* address_view_model_create(navigator_request_t* req);

END_C_DECLS

#endif /*TK_ADDRESS_VIEW_MODEL_H*/
