
/*This file is generated by code generator*/

#include "room_settings.h"
#include "mvvm/base/view_model.h"

#ifndef TK_ROOMSETTINGS_VIEW_MODEL_H
#define TK_ROOMSETTINGS_VIEW_MODEL_H

BEGIN_C_DECLS
/**
 * @class room_settings_view_model_t
 *
 * view model of RoomSettings
 *
 */
typedef struct _room_settings_view_model_t {
  view_model_t view_model;

  /*model object*/
  RoomSettings* aRoomSettings;
} room_settings_view_model_t;

/**
 * @method room_settings_view_model_create
 * 创建RoomSettings view model对象。
 *
 * @annotation ["constructor"]
 * @param {navigator_request_t*} req 请求参数。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* room_settings_view_model_create(navigator_request_t* req);

/**
 * @method room_settings_view_model_create_with
 * 创建RoomSettings view model对象。
 *
 * @annotation ["constructor"]
 * @param {RoomSettings*}  aRoomSettings RoomSettings对象。
 *
 * @return {view_model_t} 返回view_model_t对象。
 */
view_model_t* room_settings_view_model_create_with(RoomSettings* aRoomSettings);

/**
 * @method room_settings_view_model_attach
 * 关联到RoomSettings对象。
 *
 * @param {view_model_t*} view_model view_model对象。
 * @param {RoomSettings*} RoomSettings RoomSettings对象。
 *
 * @return {ret_t} 返回RET_OK表示成功，否则表示失败。
 */
ret_t room_settings_view_model_attach(view_model_t* vm, RoomSettings* aRoomSettings);

END_C_DECLS

#endif /*TK_ROOMSETTINGS_VIEW_MODEL_H*/
