#include "awtk.h"
#include "base/assets_manager.h"
#ifndef WITH_FS_RES
extern TK_CONST_DATA_ALIGN(const unsigned char strings_zh_CN[]);
extern TK_CONST_DATA_ALIGN(const unsigned char strings_en_US[]);
extern TK_CONST_DATA_ALIGN(const unsigned char style_main[]);
extern TK_CONST_DATA_ALIGN(const unsigned char style_dialog_toast[]);
extern TK_CONST_DATA_ALIGN(const unsigned char style_keyboard[]);
extern TK_CONST_DATA_ALIGN(const unsigned char style_default[]);
extern TK_CONST_DATA_ALIGN(const unsigned char style_dialog_info[]);
extern TK_CONST_DATA_ALIGN(const unsigned char style_file_browser[]);
extern TK_CONST_DATA_ALIGN(const unsigned char style_dialog_confirm[]);
extern TK_CONST_DATA_ALIGN(const unsigned char style_window1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char style_dialog[]);
extern TK_CONST_DATA_ALIGN(const unsigned char style_dialog_warn[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_kb_ascii[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_temperature1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_temperature19[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_calculator[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_shape[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_kb_phone[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_temperature14[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_temperature10[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_temperature1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_room_settings[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_kb_int[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_kb_hex[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_calculator[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_shape[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_temperature6[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_temperature17[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_home[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_humidity[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_humidity[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_folder_chooser[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_kb_float[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_temperature6[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_com_settings[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_temperature4[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_file_chooser_for_open[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_temperature9[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_home[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_temperature5[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_temperature_humidity[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_temperature4[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_temperature9[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_temperature18[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_temperature14[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_temperature5[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_temperature10[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_room_settings[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_books[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_demo9_main[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_temperature3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_temperature17[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_temperature2[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_file_chooser_for_save[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_temperature_humidity[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_temperature3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_books[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_custom_handlers[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_kb_ufloat[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_temperature16[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_kb_default[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_temperature2[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_demo9_main[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_js_address[]);
extern TK_CONST_DATA_ALIGN(const unsigned char ui_kb_uint[]);
#ifdef WITH_STB_IMAGE
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani6[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_checked[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_7[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_close_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_6[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bg_landscape_1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_shift[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani7[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ania[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_anic[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_earth[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani5[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_flag_none[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bee[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_contact[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bg_landscape_3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_battery_4[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_4[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_fg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_contact_active[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_close_d[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_dialog_title[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_battery_5[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_5[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bg_landscape_2[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani4[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_anib[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_me_active[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_file[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_up_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_left_on[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_battery_1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_right_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_v_fg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_empty[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_rgba[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_0[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_battery_0[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_edit_clear_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_up_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_visible[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_left_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_clock_second[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_battery_2[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_2[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_en[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_drag_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_guage_bg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_battery_3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani2[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_left_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_middle_on[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bricks[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_msg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_play_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_play_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_msg_active[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_radio_checked[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_active_dot[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_zh[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_question[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_discovery_active[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_dot[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_shifton[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_check[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_cursor[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_me[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_info[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_red_btn_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_middle_off[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_down_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_return_up[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_green_btn_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_green_btn_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_muted[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_down_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_rgb[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_dot[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_unmuted[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_right_off[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_message[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_play_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_2[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_bg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_right_on[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_guage_pointer[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_flag_US[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_left_off[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_progress_circle[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_red_btn_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_drag[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bg_portrait_1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_unchecked[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_red_btn_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_down_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_v_bg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_warn[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bg_portrait_3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_green_btn_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bg_portrait_2[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_flag_CN[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_switch[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_radio_unchecked[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_close_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_close_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_clock_bg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_clock_minute[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_cross[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_clock[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_find[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani9[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_up_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_edit_clear_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_folder[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_8[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_right_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_discovery[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_right_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_9[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_edit_clear_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani8[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_logo[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_invisible[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_drag_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_backspace[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_left_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_clock_hour[]);
#else
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_right_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_4[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_close_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_battery_1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_bg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_progress_circle[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_muted[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_file[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_8[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_earth[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_flag_none[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_shift[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_up_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_discovery_active[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_en[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_right_on[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_discovery[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_rgb[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_9[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_dot[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani2[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_battery_0[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_find[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_fg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_close_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_left_on[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_question[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_invisible[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_guage_bg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_5[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_dot[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_right_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bee[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_visible[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_clock_bg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_me_active[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_cursor[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_clock_minute[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_switch[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_checked[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_middle_off[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_close_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_folder[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_zh[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_right_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani9[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_anib[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_2[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_up_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_clock[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_empty[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bg_portrait_1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani5[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani4[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bg_landscape_1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_left_off[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_radio_unchecked[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_rgba[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_shifton[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_up_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_msg_active[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_anic[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani8[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_active_dot[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_guage_pointer[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_close_d[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_right_off[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_unmuted[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_cross[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_backspace[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_left_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_edit_clear_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_clock_second[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_contact[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bricks[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_dialog_title[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani7[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_play_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_battery_5[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bg_landscape_2[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bg_portrait_3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_green_btn_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_red_btn_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_me[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_0[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_down_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_warn[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_contact_active[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_drag_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bg_portrait_2[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_battery_4[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_bg_landscape_3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani6[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_message[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_edit_clear_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ania[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ani1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_battery_3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_logo[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_left_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_2[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_6[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_check[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_return_up[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_middle_on[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_down_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_radio_checked[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_red_btn_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_green_btn_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_v_bg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_clock_hour[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_flag_CN[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_play_o[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_play_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_drag[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_unchecked[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_green_btn_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_red_btn_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_drag_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_slider_v_fg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_down_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_info[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_flag_US[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_msg[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_num_7[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_3[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_arrow_left_n[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_edit_clear_p[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_battery_2[]);
#endif /*WITH_STB_IMAGE*/
#ifdef WITH_VGCANVAS
extern TK_CONST_DATA_ALIGN(const unsigned char image_pointer_4[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_ball[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_china[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_pointer_1[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_pointer[]);
extern TK_CONST_DATA_ALIGN(const unsigned char image_girl[]);
#endif /*WITH_VGCANVAS*/
#if defined(WITH_STB_FONT) || defined(WITH_FT_FONT)
extern TK_CONST_DATA_ALIGN(const unsigned char font_ap[]);
extern TK_CONST_DATA_ALIGN(const unsigned char font_default_full[]);
extern TK_CONST_DATA_ALIGN(const unsigned char font_default[]);
#else  /*WITH_STB_FONT or WITH_FT_FONT*/
extern TK_CONST_DATA_ALIGN(const unsigned char font_default_20[]);
extern TK_CONST_DATA_ALIGN(const unsigned char font_default_16[]);
extern TK_CONST_DATA_ALIGN(const unsigned char font_default_18[]);
extern TK_CONST_DATA_ALIGN(const unsigned char font_default_96[]);
extern TK_CONST_DATA_ALIGN(const unsigned char font_default_32[]);
extern TK_CONST_DATA_ALIGN(const unsigned char font_default_24[]);
#endif /*WITH_STB_FONT or WITH_FT_FONT*/
extern TK_CONST_DATA_ALIGN(const unsigned char script_home[]);
extern TK_CONST_DATA_ALIGN(const unsigned char script_shape[]);
extern TK_CONST_DATA_ALIGN(const unsigned char script_temperature[]);
extern TK_CONST_DATA_ALIGN(const unsigned char script_books[]);
extern TK_CONST_DATA_ALIGN(const unsigned char script_address[]);
extern TK_CONST_DATA_ALIGN(const unsigned char script_temperature_ex[]);
extern TK_CONST_DATA_ALIGN(const unsigned char script_humidity[]);
extern TK_CONST_DATA_ALIGN(const unsigned char script_temperature_timer[]);
extern TK_CONST_DATA_ALIGN(const unsigned char script_com_settings[]);
extern TK_CONST_DATA_ALIGN(const unsigned char script_room_settings[]);
extern TK_CONST_DATA_ALIGN(const unsigned char script_calculator[]);
#endif /*WITH_FS_RES*/

ret_t assets_init_dark(void) {
  assets_manager_t* am = assets_manager();

#ifdef WITH_FS_RES
  assets_manager_preload(am, ASSET_TYPE_FONT, "default");
  assets_manager_preload(am, ASSET_TYPE_STYLE, "default");
#else
  assets_manager_add(am, strings_zh_CN);
  assets_manager_add(am, strings_en_US);
  assets_manager_add(am, style_main);
  assets_manager_add(am, style_dialog_toast);
  assets_manager_add(am, style_keyboard);
  assets_manager_add(am, style_default);
  assets_manager_add(am, style_dialog_info);
  assets_manager_add(am, style_file_browser);
  assets_manager_add(am, style_dialog_confirm);
  assets_manager_add(am, style_window1);
  assets_manager_add(am, style_dialog);
  assets_manager_add(am, style_dialog_warn);
  assets_manager_add(am, ui_kb_ascii);
  assets_manager_add(am, ui_js_temperature1);
  assets_manager_add(am, ui_temperature19);
  assets_manager_add(am, ui_calculator);
  assets_manager_add(am, ui_js_shape);
  assets_manager_add(am, ui_kb_phone);
  assets_manager_add(am, ui_temperature14);
  assets_manager_add(am, ui_js_temperature10);
  assets_manager_add(am, ui_temperature1);
  assets_manager_add(am, ui_js_room_settings);
  assets_manager_add(am, ui_kb_int);
  assets_manager_add(am, ui_kb_hex);
  assets_manager_add(am, ui_js_calculator);
  assets_manager_add(am, ui_shape);
  assets_manager_add(am, ui_temperature6);
  assets_manager_add(am, ui_js_temperature17);
  assets_manager_add(am, ui_js_home);
  assets_manager_add(am, ui_humidity);
  assets_manager_add(am, ui_js_humidity);
  assets_manager_add(am, ui_folder_chooser);
  assets_manager_add(am, ui_kb_float);
  assets_manager_add(am, ui_js_temperature6);
  assets_manager_add(am, ui_js_com_settings);
  assets_manager_add(am, ui_temperature4);
  assets_manager_add(am, ui_file_chooser_for_open);
  assets_manager_add(am, ui_js_temperature9);
  assets_manager_add(am, ui_home);
  assets_manager_add(am, ui_js_temperature5);
  assets_manager_add(am, ui_temperature_humidity);
  assets_manager_add(am, ui_js_temperature4);
  assets_manager_add(am, ui_temperature9);
  assets_manager_add(am, ui_js_temperature18);
  assets_manager_add(am, ui_js_temperature14);
  assets_manager_add(am, ui_temperature5);
  assets_manager_add(am, ui_temperature10);
  assets_manager_add(am, ui_room_settings);
  assets_manager_add(am, ui_js_books);
  assets_manager_add(am, ui_js_demo9_main);
  assets_manager_add(am, ui_js_temperature3);
  assets_manager_add(am, ui_temperature17);
  assets_manager_add(am, ui_temperature2);
  assets_manager_add(am, ui_file_chooser_for_save);
  assets_manager_add(am, ui_js_temperature_humidity);
  assets_manager_add(am, ui_temperature3);
  assets_manager_add(am, ui_books);
  assets_manager_add(am, ui_custom_handlers);
  assets_manager_add(am, ui_kb_ufloat);
  assets_manager_add(am, ui_temperature16);
  assets_manager_add(am, ui_kb_default);
  assets_manager_add(am, ui_js_temperature2);
  assets_manager_add(am, ui_demo9_main);
  assets_manager_add(am, ui_js_address);
  assets_manager_add(am, ui_kb_uint);
  assets_manager_add(am, image_arrow_right_o);
  assets_manager_add(am, image_num_4);
  assets_manager_add(am, image_close_o);
  assets_manager_add(am, image_battery_1);
  assets_manager_add(am, image_slider_bg);
  assets_manager_add(am, image_ani3);
  assets_manager_add(am, image_progress_circle);
  assets_manager_add(am, image_muted);
  assets_manager_add(am, image_file);
  assets_manager_add(am, image_num_8);
  assets_manager_add(am, image_earth);
  assets_manager_add(am, image_flag_none);
  assets_manager_add(am, image_shift);
  assets_manager_add(am, image_arrow_up_p);
  assets_manager_add(am, image_discovery_active);
  assets_manager_add(am, image_en);
  assets_manager_add(am, image_right_on);
  assets_manager_add(am, image_discovery);
  assets_manager_add(am, image_rgb);
  assets_manager_add(am, image_num_9);
  assets_manager_add(am, image_dot);
  assets_manager_add(am, image_ani2);
  assets_manager_add(am, image_battery_0);
  assets_manager_add(am, image_find);
  assets_manager_add(am, image_slider_fg);
  assets_manager_add(am, image_close_n);
  assets_manager_add(am, image_left_on);
  assets_manager_add(am, image_1);
  assets_manager_add(am, image_question);
  assets_manager_add(am, image_invisible);
  assets_manager_add(am, image_guage_bg);
  assets_manager_add(am, image_num_5);
  assets_manager_add(am, image_num_dot);
  assets_manager_add(am, image_arrow_right_n);
  assets_manager_add(am, image_bee);
  assets_manager_add(am, image_visible);
  assets_manager_add(am, image_clock_bg);
  assets_manager_add(am, image_me_active);
  assets_manager_add(am, image_cursor);
  assets_manager_add(am, image_clock_minute);
  assets_manager_add(am, image_switch);
  assets_manager_add(am, image_checked);
  assets_manager_add(am, image_middle_off);
  assets_manager_add(am, image_close_p);
  assets_manager_add(am, image_folder);
  assets_manager_add(am, image_zh);
  assets_manager_add(am, image_arrow_right_p);
  assets_manager_add(am, image_ani9);
  assets_manager_add(am, image_anib);
  assets_manager_add(am, image_num_2);
  assets_manager_add(am, image_arrow_up_o);
  assets_manager_add(am, image_clock);
  assets_manager_add(am, image_empty);
  assets_manager_add(am, image_bg_portrait_1);
  assets_manager_add(am, image_ani5);
  assets_manager_add(am, image_ani4);
  assets_manager_add(am, image_bg_landscape_1);
  assets_manager_add(am, image_left_off);
  assets_manager_add(am, image_radio_unchecked);
  assets_manager_add(am, image_rgba);
  assets_manager_add(am, image_shifton);
  assets_manager_add(am, image_arrow_up_n);
  assets_manager_add(am, image_num_3);
  assets_manager_add(am, image_msg_active);
  assets_manager_add(am, image_anic);
  assets_manager_add(am, image_ani8);
  assets_manager_add(am, image_active_dot);
  assets_manager_add(am, image_guage_pointer);
  assets_manager_add(am, image_close_d);
  assets_manager_add(am, image_right_off);
  assets_manager_add(am, image_unmuted);
  assets_manager_add(am, image_cross);
  assets_manager_add(am, image_backspace);
  assets_manager_add(am, image_arrow_left_p);
  assets_manager_add(am, image_edit_clear_n);
  assets_manager_add(am, image_clock_second);
  assets_manager_add(am, image_contact);
  assets_manager_add(am, image_bricks);
  assets_manager_add(am, image_dialog_title);
  assets_manager_add(am, image_ani7);
  assets_manager_add(am, image_play_p);
  assets_manager_add(am, image_battery_5);
  assets_manager_add(am, image_bg_landscape_2);
  assets_manager_add(am, image_bg_portrait_3);
  assets_manager_add(am, image_green_btn_p);
  assets_manager_add(am, image_red_btn_p);
  assets_manager_add(am, image_me);
  assets_manager_add(am, image_num_0);
  assets_manager_add(am, image_arrow_down_p);
  assets_manager_add(am, image_num_1);
  assets_manager_add(am, image_warn);
  assets_manager_add(am, image_contact_active);
  assets_manager_add(am, image_slider_drag_o);
  assets_manager_add(am, image_bg_portrait_2);
  assets_manager_add(am, image_battery_4);
  assets_manager_add(am, image_bg_landscape_3);
  assets_manager_add(am, image_ani6);
  assets_manager_add(am, image_message);
  assets_manager_add(am, image_edit_clear_o);
  assets_manager_add(am, image_ania);
  assets_manager_add(am, image_ani1);
  assets_manager_add(am, image_battery_3);
  assets_manager_add(am, image_logo);
  assets_manager_add(am, image_arrow_left_o);
  assets_manager_add(am, image_2);
  assets_manager_add(am, image_num_6);
  assets_manager_add(am, image_check);
  assets_manager_add(am, image_return_up);
  assets_manager_add(am, image_middle_on);
  assets_manager_add(am, image_arrow_down_o);
  assets_manager_add(am, image_radio_checked);
  assets_manager_add(am, image_red_btn_o);
  assets_manager_add(am, image_green_btn_o);
  assets_manager_add(am, image_slider_v_bg);
  assets_manager_add(am, image_clock_hour);
  assets_manager_add(am, image_flag_CN);
  assets_manager_add(am, image_play_o);
  assets_manager_add(am, image_play_n);
  assets_manager_add(am, image_slider_drag);
  assets_manager_add(am, image_unchecked);
  assets_manager_add(am, image_green_btn_n);
  assets_manager_add(am, image_red_btn_n);
  assets_manager_add(am, image_slider_drag_p);
  assets_manager_add(am, image_slider_v_fg);
  assets_manager_add(am, image_arrow_down_n);
  assets_manager_add(am, image_info);
  assets_manager_add(am, image_flag_US);
  assets_manager_add(am, image_msg);
  assets_manager_add(am, image_num_7);
  assets_manager_add(am, image_3);
  assets_manager_add(am, image_arrow_left_n);
  assets_manager_add(am, image_edit_clear_p);
  assets_manager_add(am, image_battery_2);
#if defined(WITH_STB_FONT) || defined(WITH_FT_FONT)
  assets_manager_add(am, font_ap);
  assets_manager_add(am, font_default_full);
  assets_manager_add(am, font_default);
#else  /*WITH_STB_FONT or WITH_FT_FONT*/
  assets_manager_add(am, font_default_20);
  assets_manager_add(am, font_default_16);
  assets_manager_add(am, font_default_18);
  assets_manager_add(am, font_default_96);
  assets_manager_add(am, font_default_32);
  assets_manager_add(am, font_default_24);
#endif /*WITH_STB_FONT or WITH_FT_FONT*/
#ifdef WITH_VGCANVAS
  assets_manager_add(am, image_pointer_4);
  assets_manager_add(am, image_ball);
  assets_manager_add(am, image_china);
  assets_manager_add(am, image_pointer_1);
  assets_manager_add(am, image_pointer);
  assets_manager_add(am, image_girl);
#endif /*WITH_VGCANVAS*/
  assets_manager_add(am, script_home);
  assets_manager_add(am, script_shape);
  assets_manager_add(am, script_temperature);
  assets_manager_add(am, script_books);
  assets_manager_add(am, script_address);
  assets_manager_add(am, script_temperature_ex);
  assets_manager_add(am, script_humidity);
  assets_manager_add(am, script_temperature_timer);
  assets_manager_add(am, script_com_settings);
  assets_manager_add(am, script_room_settings);
  assets_manager_add(am, script_calculator);
#endif

  tk_init_assets();
  return RET_OK;
}
