cd ./cppdemo10; . gen.sh; cd -
cd ./cppdemo11; . gen.sh; cd -
cd ./cppdemo12; . gen.sh; cd -
cd ./cppdemo13; . gen.sh; cd -
cd ./cppdemo1; . gen.sh; cd -
cd ./cppdemo2; . gen.sh; cd -
cd ./cppdemo3; . gen.sh; cd -
cd ./cppdemo4; . gen.sh; cd -
cd ./cppdemo5; . gen.sh; cd -
cd ./cppdemo6; . gen.sh; cd -
cd ./cppdemo7; . gen.sh; cd -
cd ./cppdemo8; . gen.sh; cd -
cd ./cppdemo9; . gen.sh; cd -
cd ./demo10; . gen.sh; cd -
cd ./demo11; . gen.sh; cd -
cd ./demo12; . gen.sh; cd -
cd ./demo13; . gen.sh; cd -
cd ./demo14; . gen.sh; cd -
cd ./demo16; . gen.sh; cd -
cd ./demo1; . gen.sh; cd -
cd ./demo20; . gen.sh; cd -
cd ./demo2; . gen.sh; cd -
cd ./demo3; . gen.sh; cd -
cd ./demo4; . gen.sh; cd -
cd ./demo5; . gen.sh; cd -
cd ./demo6; . gen.sh; cd -
cd ./demo7; . gen.sh; cd -
cd ./demo8; . gen.sh; cd -
cd ./demo9; . gen.sh; cd -
