import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

env.Program(os.path.join(BIN_DIR, 'demo1'), Glob('demo1/*.c') + ["assets.c"])
env.Program(os.path.join(BIN_DIR, 'demo2'), Glob('demo2/*.c') + ["assets.c"])
env.Program(os.path.join(BIN_DIR, 'demo3'), Glob('demo3/*.c') + ["assets.c"])
env.Program(os.path.join(BIN_DIR, 'demo4'), Glob('demo4/*.c') + ["assets.c"])
env.Program(os.path.join(BIN_DIR, 'demo5'), Glob('demo5/*.c') + ["assets.c"])
env.Program(os.path.join(BIN_DIR, 'demo6'), Glob('demo6/*.c') + ["assets.c"])
env.Program(os.path.join(BIN_DIR, 'demo7'), Glob('demo7/*.c') + ["assets.c"])
env.Program(os.path.join(BIN_DIR, 'demo8'), Glob('demo8/*.c') + ["assets.c"])

env.Program(os.path.join(BIN_DIR, 'jsdemo1'), Glob('jsdemo1/*.c') + ["assets.c"])
env.Program(os.path.join(BIN_DIR, 'jsdemo2'), Glob('jsdemo2/*.c') + ["assets.c"])
env.Program(os.path.join(BIN_DIR, 'jsdemo3'), Glob('jsdemo3/*.c') + ["assets.c"])
env.Program(os.path.join(BIN_DIR, 'jsdemo4'), Glob('jsdemo4/*.c') + ["assets.c"])
