import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

env.Program(os.path.join(BIN_DIR, 'demo1'), Glob('demo1/*.c') + ["assets.c"])
env.Program(os.path.join(BIN_DIR, 'demo2'), Glob('demo2/*.c') + ["assets.c"])
env.Program(os.path.join(BIN_DIR, 'demo3'), Glob('demo3/*.c') + ["assets.c"])
env.Program(os.path.join(BIN_DIR, 'demo4'), Glob('demo4/*.c') + ["assets.c"])
