import os

LIB_DIR=os.environ['LIB_DIR'];
BIN_DIR=os.environ['BIN_DIR'];

sources= Glob('mvvm/base/*.c') + \
  Glob('mvvm/hardware/*.c') +  \
  Glob('mvvm/awtk/*.c') + \
  Glob('mvvm/jerryscript/*.c') + \
  Glob('mvvm/cpp/*.cpp') + \
  Glob('mvvm/*.c')

env=DefaultEnvironment().Clone()
env.Library(os.path.join(LIB_DIR, 'mvvm'), sources)

